# -*- coding: utf-8 -*-
"""Rock_Paper_Scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJ6MWRTyvPqy0y-2ynvntLCkmVm9lvuw
"""

import random
import os

Win_List = [('Rock', 'Scissors'),  # Rock beats Scissors
            ('Scissors', 'Paper'),  # Scissors beat Paper
            ('Paper', 'Rock')]  # Paper beats Rock

Selection_List = ['Rock', 'Paper', 'Scissors']

stats_count = {'Player': 0, 'Computer': 0, 'Ties': 0}

def Clear_All():
    """ Clears the screen based on the operating system. """
    if os.name == "posix":
        os.system('clear')
    elif os.name in ("nt", "dos", "ce"):
        os.system('CLS')

def Play():
    """ Main function to play Rock Paper Scissors. """
    Clear_All()
    Introduction = (" Let's play ROCK PAPER SCISSORS!")
    Options = ("\n Following are the simple rules to play:"
               "\n *You have to choose between: Rock, Paper or Scissors."
               "\n\n You must know that:"
               "\n *Rock crushes Scissors."
               "\n *Scissors cut Paper."
               "\n *Paper covers Rock."
               "\n\n Notes: *The first one that scores 3 points will be the WINNER!"
               "\n        *Type 'Help' in case you forgot the rules."
               "\n        *Type 'Exit' in case you want to exit the game.\n")

    print(Introduction)
    print(Options)

    while True:
        Select_Player = input("Your Selections are {}: ".format(Selection_List))
        Select_Player = Select_Player.capitalize()  # Capitalize to match 'Rock', 'Paper', 'Scissors'

        if Select_Player in Selection_List:
            Clear_All()
            Select_Computer = random.choice(Selection_List)

            print("Player Selection: {}".format(Select_Player))
            print("Computer Selection: {}".format(Select_Computer))

            match = (Select_Player, Select_Computer)

            if Select_Player == Select_Computer:
                stats_count['Ties'] += 1
                print("\nResult: Both chose {}! It's a Tie!".format(Select_Player))
            elif match in Win_List:
                stats_count['Player'] += 1
                print("\nResult: {} beats {}! Congrats, You Won!".format(Select_Player, Select_Computer))
            else:
                stats_count['Computer'] += 1
                print("\nResult: {} beats {}! Sorry, You Lost!".format(Select_Computer, Select_Player))

            print("-------  STATS  -------"
                  "\n You  | Computer | Ties"
                  "\n  {Player}        {Computer}        {Ties}"
                  "\n-----------------------".format(**stats_count))

            if stats_count['Player'] == 3:
                print(" Congratulations! You Won!")
                break
            elif stats_count['Computer'] == 3:
                print("Sorry! You Lost")
                break

        elif Select_Player == 'Help':  # If user asks for help
            Clear_All()
            print(Options)
        elif Select_Player == 'Exit':  # If user wants to exit
            print("Bye!")
            break
        else:
            print("Invalid selection. Try again...")

Play()